Algoritmo "soma"
// 
//  
// Descrição   : soma dois numeros
// Autor(a)    : Mateus Samuel Oiveira de Espindola
// Data atual  : 20/08/2024
Var
   n1, n2, soma : real


Inicio
      escreval("Soma de dois numeros")
      escreva("Digite o primeiro numero: ")
      leia(n1)
      escreva("Digite o segundo numero: ")
      leia(n2)
      
      soma <- n1+n2
      
      escreval("A soma é", soma)


Fimalgoritmo