Algoritmo "troca_variavel"
// 
//  
// Descrição   : inverte os valores das variaveis n1 e n2
// Autor(a)    : Mateus Samuel Oliveira de Espindola
// Data atual  : 20/08/2024
Var
   n1, n2, n3 : inteiro


Inicio
      n1 <- 23
      n2 <- 30
      
      escreval("n1 =", n1, " n2 =", n2)
      
      n3 <- n1
      n1 <- n2
      n2 <- n3
      
      escreval("n1 =", n1, " n2 =", n2)

Fimalgoritmo