Algoritmo "semnome"
// 
//  
// Descrição   : par ou impar
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/08/2024
Var
   n1 : inteiro


Inicio
      escreval("|===== PAR OU IMPAR =====|")
      escreva("Digite um numero inteiro: ")
      leia(n1)
      
      limpatela
      se (n1%2)=0 entao
         escreval(n1, " é par!")
      senao
           escreval(n1, " é impar!")
      fimse


Fimalgoritmo